# Generated by Django 4.2.5 on 2023-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Назва задачі')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Закінчено')),
            ],
            options={
                'verbose_name': 'Задачі',
                'verbose_name_plural': 'Задачі',
            },
        ),
    ]
