# Generated by Django 4.2.5 on 2023-09-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_task',
        ),
        migrations.AddField(
            model_name='user',
            name='user_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.todo'),
            preserve_default=False,
        ),
    ]
