# Generated by Django 4.2.5 on 2023-09-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todo_user_task_user_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.todo'),
        ),
    ]
