# Generated by Django 4.2.5 on 2023-09-30 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_user_user_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_task',
        ),
        migrations.AddField(
            model_name='todo',
            name='user_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
